name: Semantic Release

on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: matteo4diani/poetry-semantic-release@v0
        with:
          github-token: ${{ secrets.REPO_ADMIN_TOKEN }}
          pypi-token: ${{ secrets.PYPI_TOKEN }}
      #      - uses: actions/checkout@v4
      #        with:
      #          fetch-depth: 0
      #          token: ${{ secrets.REPO_ADMIN_TOKEN }}
      #
      #      - name: Set up Python 3.10
      #        uses: actions/setup-python@v4
      #        with:
      #          python-version: '3.10'
      #          cache: 'pip'
      #
      #      - name: Install Poetry
      #        uses: snok/install-poetry@v1
      #        with:
      #          virtualenvs-create: false
      #
      #      - name: Run poetry
      #        run: |
      #          poetry install
      #
      #      - name: Python Semantic Release
      #        uses: relekang/python-semantic-release@master
      #        with:
      #          github_token: ${{ secrets.REPO_ADMIN_TOKEN }}
      #
      #  publish:
      #    needs: release
      #    runs-on: ubuntu-latest
      #    steps:
      #      - uses: actions/checkout@v4
      #
      #      - name: Set up Python
      #        uses: actions/setup-python@v4
      #        with:
      #          python-version: '3.x'
      #          cache: 'pip'
      #
      #      - name: Install dependencies
      #        run: |
      #          python -m pip install --upgrade pip
      #          pip install build
      #
      #      - name: Build package
      #        run: python -m build
      #
      #      - name: Publish package
      #        uses: pypa/gh-action-pypi-publish@release/v1
      #        with:
      #          user: __token__
      #          password: ${{ secrets.PYPI_TOKEN }}
