name: Semantic Release

permissions:
  contents: write
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false

      - name: Cache poetry dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

      - name: Run poetry
        run: |
          poetry install

      - name: Semantic Release
        run: |
          pip install python-semantic-release
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          semantic-release publish -D commit_author="github-actions <actions@github.com>"
        env: GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
